### ISSUE TITLE
ag-grid return all updated data in grid

### ISSUE THREAD

**Issue by rroyer-xyz** [justpy-org/justpy#138]
Hello,

I have a case where users are making updates to the grid (e.g., adding new blank rows via a button, updating cell values in a row by clicking on a cell and typing, re-ordering rows).

They also have a "Save" button to save the updates that have been made to the grid. Is there a way when this "Save" button is clicked to read in all the updated data in the grid?

I was looking into using the code below; however, I need to store this grid data as a python variable so that I can perform additional actions. Any thoughts on how best to return all grid data and store as a python variable?

```
async def save_clicked(self, msg):
    await self.grid.run_api('getDataAsCsv()', msg.page)

    ## need something like this...
    my_data = await self.grid.run_api('getDataAsCsv()', msg.page)
```

**Comment by rroyer-xyz** [comment]
Thanks, this should be good enough for now

**Comment by WolfgangFahl** [comment]
Is this for Milestone 0.3.0 or should it be moved to ideas?

**Comment by WolfgangFahl** [comment]
In our implementations we kept a copy of the original list of dicts in background. See e.g. https://github.com/WolfgangFahl/pyCEURmake/blob/fbc35c01f5f8959b1f5fa6658b58f21e4d415976/ceurws/volumebrowser.py#L761
