### ISSUE TITLE
QDate infinite event loop

### ISSUE THREAD

**Issue by msrkala** [justpy-org/justpy#150]
Hi, i try to localize QDate component from tutorial example (https://justpy.io/quasar_tutorial/QDate/). But it ends in infinite event loop:

`INFO justpy: In event handler: websocket {'type': 'event', 'event_data': {'event_type': 'input', 'id': 197, 'class_name': 'QDate', 'html_tag': 'q-date', 'vue_type': 'quasar_component', 'input_type': 'text', 'value': '2020-09-15 17:00', 'page_id': 0, 'websocket_id': 0, 'aux': ['locale'], 'session_id': '4bb80e1d224b42978d65201155df8c23', 'msg_type': 'event'}}`

My code:
```
import justpy as jp

class QInputDateTime(jp.QInput):


    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.mask = '####-##-## ##:##'
        date_slot = jp.QIcon(name='event', classes='cursor-pointer')
        c2 = jp.QPopupProxy(transition_show='scale', transition_hide='scale', a=date_slot)
        self.date = jp.QDate(mask='YYYY-MM-DD HH:mm', name='date', a=c2,
                             locale={
                                 'days': 'Neděle_Pondělí_Úterý_Středa_Čtvrtek_Pátek_Sobota'.split('_'),
                                 'daysShort': 'Ne_Po_Út_St_Čt_Pá_So'.split('_'),
                                 'months': 'Leden_Únor_Březen_Duben_Květen_Červen_Červenec_Srpen_Září_Říjen_Listopad_Prosinec'.split(
                                     '_'),
                                 'monthsShort': 'Led_Úno_Bře_Dub_Kvě_Čvn_Čvc_Srp_Zář_Říj_Lis_Pro'.split('_')
                             },
                             )

        time_slot = jp.QIcon(name='access_time', classes='cursor-pointer')
        c2 = jp.QPopupProxy(transition_show='scale', transition_hide='scale', a=time_slot)
        self.time = jp.QTime(mask='YYYY-MM-DD HH:mm', format24h=True, name='time', a=c2)

        self.date.parent = self
        self.time.parent = self
        self.date.value = self.value
        self.time.value = self.value
        self.prepend_slot = date_slot
        self.append_slot = time_slot
        self.date.on('input', self.date_time_change)
        self.time.on('input', self.date_time_change)
        self.on('input', self.input_change)

    @staticmethod
    def date_time_change(self, msg):
        print(self.value)
        self.parent.value = self.value
        self.parent.date.value = self.value
        self.parent.time.value = self.value

    @staticmethod
    def input_change(self, msg):
        self.date.value = self.value
        self.time.value = self.value


def input_test():
    wp = jp.QuasarPage()
    QInputDateTime(filled=True, style='width: 600px', a=wp, classes="q-pa-md", value='')
    QInputDateTime(filled=True, style='width: 600px', a=wp, classes="q-pa-md", value='2020-03-01 12:44')
    QInputDateTime(filled=True, style='width: 600px', a=wp, classes="q-pa-md", value='2021-04-01 14:44')
    QInputDateTime(filled=True, style='width: 600px', a=wp, classes="q-pa-md", value='2022-05-01 18:44')
    return wp


jp.justpy(input_test)
```

**Comment by elimintz** [comment]
Your program works well for me so I think it may be related to this issue: https://github.com/elimintz/justpy/issues/148
Please install websockets:
`pip install websockets`

and let me know if this solves the problem.

**Comment by msrkala** [comment]
@elimintz Unfortunately, it didn't help.

```
pip freeze

addict==2.3.0
aiofiles==0.5.0
certifi==2020.6.20
click==7.1.2
demjson==2.2.4
h11==0.11.0
httpcore==0.12.0
httptools==0.1.1
httpx==0.16.1
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.2
justpy==0.1.4
MarkupSafe==1.1.1
python-dotenv==0.14.0
PyYAML==5.3.1
rfc3986==1.4.0
sniffio==1.1.0
starlette==0.13.8
uvicorn==0.12.1
uvloop==0.14.0
watchgod==0.6
websockets==8.1
```

I tried chrome, firefox and safari. It only works in safari browser. I suppose, that safari blocks the javascript loop.
Can i give you any other info?

Thank you for your time.

**Comment by elimintz** [comment]
Perhaps I am not reproducing the bug correctly. I ran the program you sent and tried the different input boxes with no problem. What do you do exactly for the problem to emerge?

**Comment by elimintz** [comment]
Ok, adding 
`NO_INTERNET = False`

to justpy.env will likely solve your problem. I was able to replicate the bug without it and adding that line solves the problem.

The issue is the version of Quasar that comes by default with JustPy. It is an older version and gets stale between releases.

**Comment by msrkala** [comment]
@elimintz Unfortunately, it still doesn't work.

My steps to reproduce:
- run program
- click on calendar icon to open QDate dialog
- pick the new date

Infinitive print of new picked value in console.

**Comment by elimintz** [comment]
Yes, I see that now. The input event for some reason keeps being generated when `locale` is set. Very strange.
I'll try to figure this out over the weekend.

**Comment by msrkala** [comment]
@elimintz Thank you, for your time.

For people that end up, there is a workaround mentioned here #84. To close QDate dialog right after date picked `await self.q_popup_proxy.run_method('hide()', msg.websocket) `.

Unfortunately, it doesn't cover my use case.

**Comment by WolfgangFahl** [comment]
http://jpdemo.bitplan.com/ has a qdate_issue 150 example now and the problem is reproducible

**Comment by tholzheim** [comment]
This was a though one

When selecting a new date over the date selector popup an input event with the resaon `day` is emited.

> see https://github.com/quasarframework/quasar/blob/7905160ca2e287d1e42aa2ded311f130b3f2d567/ui/src/components/date/QDate.js#L686

> see https://github.com/quasarframework/quasar/blob/7905160ca2e287d1e42aa2ded311f130b3f2d567/ui/src/components/date/QDate.js#L724

The update is handled correctly by justpy and  on the client side the QDate value is updated.
During the update the property computedLocale is updated.
Unfortunatly, this property has a watcher which triggers a input event with the reason `locale`. 



> see https://github.com/quasarframework/quasar/blob/7905160ca2e287d1e42aa2ded311f130b3f2d567/ui/src/mixins/datetime.js#L38-L50

Unfortunatly, this property has a watcher which triggers a input event with the reason `locale`. 
The reason is for no case transfered to justpy and thus justpy only receives an input event with the QDate value.
The input event therefore triggers an update and the loop begins...

> When removing the locals the `local` event is not triggered and the date can be selected normally


To resolve the issue we could adjust this section 
https://github.com/justpy-org/justpy/blob/faa8c20d435e2cb5f60b3b26fe4f354719333ea0/justpy/templates/js/vue/quasar_component.js#L177-L188

To 
```js
inputEvent: (function (event) {
            if (arguments.length == 1) {
                aux = false;
            } else {
                var aux = [];
                for (var i = 1; i < arguments.length; i++) {
                    aux.push(arguments[i]);
                }
            }
            if (event == null && this.$props.jp_props.html_tag == 'q-input') event = '';
            if (event != null && this.$props.jp_props.class_name === 'QDate'){
                let reason = aux[0]
                if (reason === 'locale') return;
            }
            this.eventFunction(event, 'input', aux);
        }),
```

to catch the input events with reason `locale` and to avoid the infinite event loop.
> Since I am not familiar enough with Quasar I do not know how often an event with a corresponding reason is used and if the resaon object should be properly integrated into the Quasar components.

**Comment by tholzheim** [comment]
Issue #212 is related as access to the event reason in justpy is discussed

**Comment by WolfgangFahl** [comment]
@tholzheim  very good analysis which helps finding a systematic solution for similar issues.

**Comment by WolfgangFahl** [comment]
If you run into this bug you might want to migrate to nicegui
