### ISSUE TITLE
Default static directory vs. justpy.env file location

### ISSUE THREAD

**Issue by platinops** [justpy-org/justpy#162]
According to the [docs](https://justpy.io/reference/configuration/), the justpy.env file should be in the directory from which the program is run. The default static directory however is the same folder: 

`STATIC_DIRECTORY = config('STATIC_DIRECTORY', cast=str, default=os.getcwd())`

This means, by the default, the justpy.env (possibly containing sensitive information) can be reached at http://localhost:8000/static/justpy.env

Isn't this a security flaw? Might be better to change the default to the module directory as with the templates:

`STATIC_DIRECTORY = config('STATIC_DIRECTORY', cast=str, default=f'current_dir + '/static')`

And include the default JustPy favicon there as well? So the favicon also works in the NO_INTERNET scenario.

**Comment by elimintz** [comment]
Yes, this is a security flaw. Thanks for catching it. 
I'll try to think of a non-breaking way to solve this, if not, I will adopt your suggestion. 

Workaround for people reading this: ALWAYS specify a different STATIC_DIRECTORY in justpy.env

**Comment by platinops** [comment]
Thanks for the feedback. Even with a solution in place, might be useful to mention in the [docs](https://justpy.io/reference/configuration/) not to use the working dir as a static folder..

**Comment by platinops** [comment]
As far as I see, this has not been fixed in the recently released version 2 of Justpy?

**Comment by elimintz** [comment]
Yes, this fell through the cracks. I couldn't think of a non breaking solution and put is aside. Will revisit.

**Comment by onezerobinary** [comment]
Is this still an open issue? With the following code I'm still getting the error : **"GET /papillon.jpg HTTP/1.1" 404 Not Found**
even if the papillon.jpg file is stored on the root folder of the project.

```
app = jp.app

@jp.SetRoute('/')
def static_test():
    wp = jp.WebPage()
    jp.Img(src='/static/papillon.jpg', a=wp, classes='m-2 p-2')
    return wp

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=5005, log_level="info")
```

**Comment by WolfgangFahl** [comment]
Should IMHO be fixed ASAP to avoid followup nightmares by people who are not aware of this surprising behavior.

**Comment by WolfgangFahl** [comment]
move papillon.jpg when explaining the move of static content

**Comment by WolfgangFahl** [comment]
You might want to migrate to nicegui if you have this problem
