### ISSUE TITLE
mime type and filename of dynamic download

### ISSUE THREAD

**Issue by eudoxos** [justpy-org/justpy#180]
In this MWE, `/download_zip` should cause download of on-demand file with user-set `Content-type` and `Content-disposition`. As far I see, this is currently not possible with JustPy (starlette has [StreamingResponse](https://www.starlette.io/responses/#streamingresponse) just for that), could I get some inspiration how to work around that limitation? (besides writing the file on disk and serve it as a static file)

```python
import zipfile, io, sys
sys.path.append('/home/eudoxos/build/justpy')
import justpy as jp

@jp.SetRoute('/')
def main(): return jp.WebPage(components=[jp.A(text="Download ZIP",href="/download_zip")])

@jp.SetRoute('/download_zip')
def make_zip():
    wp=jp.WebPage()
    buf=io.BytesIO()
    z=zipfile.ZipFile(buf,mode='w',compression=zipfile.ZIP_DEFLATED)
    z.writestr('something.txt','Something.')
    z.writestr('something-else.txt','Something else.')
    wp.html=buf.getvalue()
    # returns webpage with ZIP writtes byte's repr, not data itself (see image below)
    return wp

jp.justpy()
```

![image](https://user-images.githubusercontent.com/1029876/100874423-d94e4b80-34a4-11eb-835b-4ffb06c7d03f.png)

**Comment by elimintz** [comment]
I need to think about this. Maybe this discussion https://github.com/tiangolo/fastapi/issues/58 can provide some inspiration meanwhile.

**Comment by eudoxos** [comment]
As a suggestion, trivial PR #182 allows returning starlette Response object. The example below then downloads the dynamically-generated file.

It is important to create the href with `target="_blank"` which will open a new tab (it closes immediately when the download starts); without it, connection to the page would be interrupted (`click OK to reload`).

```python
import zipfile, io, sys
import justpy as jp
import starlette.responses

@jp.SetRoute('/')
def main(): return jp.WebPage(components=[jp.A(text="Download ZIP",href="/download_zip",target="_blank")])

@jp.SetRoute('/download_zip')
def make_zip():
    wp=jp.WebPage()
    buf=io.BytesIO()
    z=zipfile.ZipFile(buf,mode='w',compression=zipfile.ZIP_DEFLATED)
    z.writestr('something.txt','Something.')
    z.writestr('something-else.txt','Something else.')
    buf.seek(0)
    return starlette.responses.StreamingResponse(
        content=buf,
        headers={'Content-Disposition':'attachment; filename="myfancyname.zip"'},
        media_type='application/zip'
    )
    return wp

jp.justpy()
```

**Comment by elimintz** [comment]
Nice and simple solution, thanks. I'll accept the PR and make the change for the next version. What is missing to make it a general solution, if anything?

**Comment by eudoxos** [comment]
For bypassing JustPy, it is complete as far I see.

An cool thing would be server-initiated download without opening the extra tab via `target="_blank"`, but I am not sure what is possible. And for my purposes, I am quite happy with this solution.

**Comment by sandeep-gh** [comment]
Can you elaborate on the problem? Possibly share some code to understand what the problem is?

**Comment by Lefort-Antoine** [comment]
I execute the same code than [eudoxos](https://github.com/eudoxos) commented [on 3 Dec 2020](https://github.com/elimintz/justpy/issues/180#issuecomment-737692793)
And my zipfile is empty.

**Comment by WolfgangFahl** [comment]
Will this be for version 0.0.3 or has it been done?

**Comment by WolfgangFahl** [comment]
You might want to migrate to nicegui if you have this problem
