### ISSUE TITLE
AgGrid rowClass

### ISSUE THREAD

**Issue by Killitz** [justpy-org/justpy#192]
Hi, 
can i use rowClass an rowClassRules Grid Properties in justpy? 

https://www.ag-grid.com/javascript-grid-row-styles/

Thanks

**Comment by elimintz** [comment]
I am looking into this, but you most probably need to make changes to the JavaScript of aggrid.js to make this work as a callback. Setting rowClass in the grid options does not seem to work.

**Comment by Killitz** [comment]
ok thanks, i'll wait for the update

**Comment by WolfgangFahl** [comment]
is this for milestone 0.0.3?

**Comment by WolfgangFahl** [comment]
You might want to migrate to nicegui if you have this problem
