### ISSUE TITLE
How do I draw shapes on a HighChart?

### ISSUE THREAD

**Issue by johndoe28** [justpy-org/justpy#193]
The HighCharts jsFiddle [example](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/renderer-rect-on-chart/) describes how to add a shape such as a rectangle to a HighChart. How can I retrieve the SVGRenderer object for a chart I created in justpy so that I can draw a shape on the chart?

**Comment by elimintz** [comment]
The current HighCharts component does not provide a simple way to do that. You would need to add JavaScript to the page. I will add this to future versions.

**Comment by johndoe28** [comment]
I have a Python only solution. How does one add JavaScript to a page?

**Comment by elimintz** [comment]
I was going for a web framework solution that is only Python. However, when you use JavaScript components like Highcharts and ag-grid, they have some features that require running JavaScript and for that you need build a JavaScript aspect for the component: https://justpy.io/tutorial/advanced_components/

For the feature you requested to work, I need to update the JavaScript part of the HighCharts component (also the Python part): https://github.com/elimintz/justpy/blob/master/justpy/templates/js/chartjp.js

You can also run JavaScript on a page: https://justpy.io/reference/webpage/#async-def-run_javascriptself-javascript_string-request_id-sendtrue

**Comment by WolfgangFahl** [comment]
You might want to migrate to nicegui if you have this need. The javascript integration there is better than for the original justpy implementation.
