### ISSUE TITLE
ag-grid setPinnedTopRowData

### ISSUE THREAD

**Issue by blaaaaaaa** [justpy-org/justpy#205]
Hi, not really an issue, but is it possible to use  setPinnedTopRowData for an AG-Grid. Tried a bunch of stuff but no success so far.

**Comment by elimintz** [comment]
In order for this feature to work, changes are required to the ag-grid component, on its JavaScript side. I'll take a deeper look at it and see if I can add this to the next version.

**Comment by WolfgangFahl** [comment]
milestone or idea?

**Comment by WolfgangFahl** [comment]
see https://www.ag-grid.com/archive/25.0.0/documentation/javascript/row-pinning/

**Comment by WolfgangFahl** [comment]
see #685
