### ISSUE TITLE
QDate event "navigation" not supported?

### ISSUE THREAD

**Issue by docm64** [justpy-org/justpy#212]
Hi,
I am working on my first real project with JustPy. Like the framework very much but still a lot to learn.
This is my issue:
I am using a Quasar QDate component. 
When the user navigates in the calendar, e.g. changes the month, I want to receive an event in JustPy.
According to the Quasar documentation, QDate supports an event called "navigation". However this doesn't seem to be available in JustPy.
I only receive "input" events when the user has finally selected a day.
Is there a way to catch navigation events?
Any idea is welcome.

**Comment by elimintz** [comment]
Hi,

Thank you for using JustPy. The navigation event (as well as some others) was added in Quasar version 1.13 and I have not had the opportunity to add it to JustPy. Changes are needed both on the JavaScript side (in https://github.com/elimintz/justpy/blob/master/justpy/templates/js/quasar_component.js) and the python side (https://github.com/elimintz/justpy/blob/master/justpy/quasarcomponents.py).

I will try to get to this as soon as possible.

**Comment by docm64** [comment]
Hi, it's great to receive a response so quickly.
Meanwhile I found a workaround. When setting the property `<emit_immediately=True>`, QDate fires input events, whenever the user makes any selections inside QDate. By checking the message inside the event handler, you can find out what was changed.

    def qdate_oninput(self,msg):
        if msg.aux[0]=='day':
            # user clicked on a day, use value
            print (self.value)
        else:
            # just a navigation event
            print(f'Navigation: {msg.aux[0]}')

It comes with a caveat. Even on such "navigation" events `<value>` is updated. This may lead to the situation that `<value>` returns a date which is not included in the `<options>`property.

**Comment by elimintz** [comment]
Thank you, the workaround is very helpful.

**Comment by WolfgangFahl** [comment]
see #685
