### ISSUE TITLE
User download from webapp bug?

### ISSUE THREAD

**Issue by NeoPythonProjects** [justpy-org/justpy#216]
[https://github.com/NeoPythonProjects/WebApp_TestDownloadCsv.git](url)

hi,
I have a very small webapp where I would like to offer the user to donwload a CSV file.
**this works:**
I have the download link in the about.py tab (from jutpy documentation). 
I comment everything out of the main.py file
I use the jp.Route(About.path, About.serve) statements in the about.py file, 
I run about.py
the local host home page opens up (file not found, as I ran it from about.py)
i then **manually enter "/about"** to the URL
The about page appears
I click the donwload link
it works fine. It downloads the csv file in /static/.

**here is where it breaks down**
I move the jp.Route() and jp.justpy statements to from about.py to main.py with the necessary import statements
I comment out the jp.Route() and jp.justpy statements in the about.py file
i run main.py
the local homepage appears (now NOT file ot found as i ran it from main.py), including a **hyperlink to the about page**
i click the huperlink and thus get to the about page
I click the download link on the about page (the one that worked as described above)
an EMPTY csv file is downloaded.

I'm using /static/ in the ref, including the first slash, so I don't think it's a directory issue. It feels more like a get versus post request, getting to the about page by adjusting the URL manually works, but via the hyperlink it doesn't work. Anyway, I've googled for about 2 days and have spoken to my Python tutor, who suggested I log the issue, if indeed it is an issue.

Thank you so much for your help!

**Comment by elimintz** [comment]
Hi,

Could you please post the two versions of the program? It is easier for me to work with code rather than a verbal description.

**Comment by NeoPythonProjects** [comment]
Hi, 

Thank you for your help!

In case it matters, I'm using Windows 10, and Chrome (latest version - Version 88.0.4324.150 (Official Build) (64-bit))
 
A debug-friendly version is in here (no need to comment out code, as described earlier):
[https://github.com/NeoPythonProjects/TestDownload.git](url)

**This works:**
1. run about.py from within about.py
2. browser opens local host (file not found, but that's ok)
3. manually add '/about' to URL
4. about page opens showing download file hyperlink
5. click download hyper link, csv file opens up

**This does NOT work**:
1. run main.py
2. browser opens localhost (no error this time, but showing home page which has a div and a hyperlink to about page)
3. on home  page click hyperlink to about page
4. about page opens
5. click 'donwload file'
result: "Failed - No File" - description on downloaded file icon in download bar

**about.py**
`import justpy as jp


class About:
    path = "/about"

    @classmethod
    def serve(cls, req):
        wp = jp.QuasarPage()
        download_link = jp.A(a=wp, text="Download file About", href="/static/WAO_db_downloadtest.csv",
                             download="WAO_test_about.csv")
        return wp


if __name__ == "__main__":
    jp.Route(About.path, About.serve)
    jp.justpy(port=8001)`






**main.py**
`import justpy as jp

from webapp.about import About
from webapp.home import Home


jp.Route(Home.path, Home.serve)
jp.Route(About.path, About.serve)

jp.justpy(port=8000)`

**Comment by NeoPythonProjects** [comment]
Hi, did this updated request ever reach you? It was posted 8 days ago. thank you.

**Comment by elimintz** [comment]
I'm sorry, I can't replicate the problem. Perhaps if you could create a very simple example that shows this bug I could be more helpful.

**Comment by NeoPythonProjects** [comment]
Hi, 

thanks for getting back to me. 

I'm not sure how to simplify it. The github project is as simple as it gets: it has 2 web-pages: (i) a home page which has nothing on it but a hyperlihnk to the 'about' page, and (ii) the 'about' page that has nothing on it but a download link.
Download from the 'about' page works if you run about.py, and manually add '/about' the URL. It does not if you run main.py and go to the 'about' page via hyperlink from the home page. 

If that works for you then we're stuck, and I'll have to recode in flask.

Thanks for your help.

**Comment by tholzheim** [comment]
As stated in the documentation the default static route is `/static`
https://github.com/justpy-org/justpy/blob/286424c9f8b55bc6d71187fcaeb6572a222fd22f/docs/tutorial/static.md?plain=1#L7
and the directory serving the default route is the current working directory of the main function.
https://github.com/justpy-org/justpy/blob/286424c9f8b55bc6d71187fcaeb6572a222fd22f/docs/tutorial/static.md?plain=1#L13

If you want to make the directory `os.getcwd()+/static` the serving directory for `/static` create the file `justpy.env` in your current working directory and configure the static directory as follows
```env
STATIC_DIRECTORY="./static"
```
