### ISSUE TITLE
forced cookie renewal

### ISSUE THREAD

**Issue by giodegas** [justpy-org/justpy#219]
I read how to use cookies for sessions handling from the documentation here:

https://justpy.io/tutorial/sessions/#introduction

I would appreciate to request a renew of the cookie every time a user does a logoff. 
Now I see it is recycling IDs, so user B logged after user A will have the same IDs in logs.

Is it possible to have a new ID for every login, even if at the same browser window?

Thank you.

**Comment by elimintz** [comment]
I agree it is a good idea to have an option to expire the cookie and I will add that in a future version.

But just to help me think this through, when a user logs out, why not delete the session from the session dict? That way you could use the same session_id for another user that logs in.

**Comment by giodegas** [comment]
Yes indeed, I tried to delete the session, but having an explicit expire would help a lot. Thank's.

**Comment by WolfgangFahl** [comment]
see also #529

**Comment by WolfgangFahl** [comment]
see #685
