### ISSUE TITLE
component.update() does not invoke component.react()

### ISSUE THREAD

**Issue by docm64** [justpy-org/justpy#225]
As I have webpages with many elements (e.g. 1000 Imgs) I started experiments with partial updates, i.e. `component.update()` instead of `wp.update()`. This significantly speeds up the update of the page in the browser in reaction to events.

However there are some tricky obstacles which I could solve only after a deep dive into JustPy source code. The documentation was helpful but incomplete, or I didn't find all details.

The following preconditions are needed for a successful `component.update()`
1.) All active wep pages must be included in `component.pages`. Use `component.add_page(wp)` to achieve this goal.
2.) component must have an id. First I was surprised to see that not all components will receive an id. In the default settings only components which have an event connected via `component.on(event,func)` actually are assured to have an id. But ids can be enforced by passing the argument `temp=False` when creating component.
Should you try to update a component without id, strange things will happen in your browser, so if you experience strange things in your browser, first check if component has an id. 

There is however some odd behavior which I consider a bug in JustPy. Normally, just before a component is rendered, the JustPy environment calls the `component.react()` method which you would typically override in your derived object classes. However with `component.update()` component will be rendered without invoking `component.react()`. As a workaround I wrote myself a wrapper function. But a clean solution would be to introduce the react() stub already in the class definition of JustPyBaseComponent and introduce a call to it as the first code line in method `JustPyBaseComponent.update()`.

**Comment by elimintz** [comment]
Thanks for this helpful discussion. My thinking was that the general case would be that you would update a shared component for which you would set delete_flag to False and that forces the creation of an id. But your use case of optimizing update time even for components that are not shared is interesting and in that case setting temp to False is the right way to go.

The react method is called with the data attribute of its parent, and if it des not have a parent, of the WebPage instance it is on. So when you update just a component, the framework does not have access to the data attribute it needs in order to call the react method. You need to do this explicitly. I may be missing something. How do you call the react method? What arguments do you give it in your case when you are just updating a component?

**Comment by docm64** [comment]
Hi, maybe the concept of the react() method is not fully clear to me. I am using it in the sense of reactivity like [described here](https://justpy.io/blog/reactivity/). The `data` parameter is not used in this example and so far none of the react() functions I designed ever used it. Can you point to an example that shows, when and how it should be used? That would be really helpful. In fact I am passing `self.data` as a dummy argument when I call react(), just to satisfy the function definition. Would that cause any unwanted side effects?

**Comment by elimintz** [comment]
I see what you mean. Certainly react is useful without the argument also. The react method you write can choose to ignore the argument, that will not create any problems.

The data argument is useful when you want to make just one change that influences all children. In the case of of the Date Card Component, an instance of it could be put in a container with other instances of other components and just by changing the data attribute in the parent, you could change the color scheme for all children. Again, this is not the only way to implement this, just an option that can be useful sometimes.

As for the issue with calling react on update, perhaps adding an optional flag to the component update method that determines if react is called would be a good solution? I wouldn't want to introduce a breaking change in case someone is counting on react not being called.

As for your final remark, some elements in JustPy could be added directly to the WebPage instance, and not to another element:
```python
wp = jp.WebPage()
d = jp.Div(a=wp)
```

In the example above, d does not have a parent that is an element, and so the data attribute of wp is used.

**Comment by docm64** [comment]
Ok, got your point. I would say that in your example above, d has wp as parent. But let's not argue about terms. 

I am more concerned about the topic, how `component.update()` is intended to work in more complex settings.
JustPy supports shared components which is a very nice feature and it also allows to insert the same Python instance of a component multiple times into the same DOM tree. Which is another nice feature.

In both situations, a component ends up having multiple parents. I call this the different _parent contexts_ of a component.

In the following I use the term _rendering_ in the sense of converting a JustPy component including its descendants (children, children of children, etc) into a Dict. Actually this is just the preparation of the real rendering which then happens in the browser. But I didn't find a better name so I stay with _rendering_.  

Now let's invoke `component.update()` on such a multiple-parent component. If correct rendering of this component depends on any parent context data, it should render differently, depending on the parent context. Remember, there is only one Python instance of that component and update() is invoked only once. So inside update() it would have to be checked, how often the component appears in different parent contexts and render it multiple times accordingly. The current implementation of update() does not foresee it. `component_dict` is created only once and then the same rendering is sent to all active websockets. `convert_component_to_dict()` is not aware of the parent context. The only way to allow a component to consider its parent context would be calling react() with the respective data argument followed by convert_component_to_dict() for each occurence. 

This would require an extension of the framework function. `JustpyBaseComponent.update()`. One of the practical challenges is that components don't keep track of their parents but only of their children. In order to find all different parent contexts of a component one would need to scan through the DOM trees of all webpages listed in component.pages

It would be a great and simple extension of the framework to provide a list property `HTMLBaseComponent.parents` or an iterator method `HTMLBaseComponent.parents()` . Often there are situations where I am in need of injecting parent into a child, e.g. when an event triggered on child shall modify a property of parent. Like in the following example:
```
    def btn_click(self,msg)
        self.d.text+=' world' # this modifies a parent property

    wp = jp.WebPage()
    div = jp.Div(text='Hello',a=wp)
    btn = jp.Button(text='click',a=div)
    btn.d = div # this injects parent into child 
    btn.on('click',btn_click)
```
With a 'parent' property the injection could be avoided like in this hypothetical piece of code
```
    def btn_click(self,msg)
        for parent in self.parents(): parent.text+=' world' # this modifies a parent property

    wp = jp.WebPage()
    div = jp.Div(text='Hello',a=wp)
    btn = jp.Button(text='click',a=div)
    btn.on('click',btn_click)
```
I would appreciate that extension.

**Comment by elimintz** [comment]
Just like tracking which pages a component gets added to, tracking which components a component is added to is difficult since there are so many ways to do it and many edge cases. Also, it will add a lot of overhead. I think probably the best solution, is for the programmer to do this explicitly in the specific case it is required.

**Comment by msrkala** [comment]
Hi @docm64,
i use this solution:

```
    @staticmethod
    def btn_click(d: jp.Div) -> Callable:
        def sub_btn_click(self, msg):
            d.text += ' world'

        return sub_btn_click

    wp = jp.WebPage()
    div = jp.Div(text='Hello', a=wp)
    btn = jp.Button(text='click', a=div)
    btn.on('click', btn_click(div))
```

**Comment by elimintz** [comment]
Very elegant solution!

**Comment by docm64** [comment]
Thank you for this idea. I like the concept!

**Comment by msrkala** [comment]
For component only update I use this technique:

- set temp=False
- overload component method convert_object_to_dict

Advanced example here: #251

**Comment by msrkala** [comment]
Earlier I used to detele_flag=False, while some strange thing happened as mentioned above. Thanks to this post i understand difference between temp and delete_flag.

**Comment by WolfgangFahl** [comment]
see #685
