### ISSUE TITLE
AgGrid version is 2 years old, let's update to latest v26.1.0?

### ISSUE THREAD

**Issue by BilliumMoto** [justpy-org/justpy#314]
The two ag-grid js files in justpy/templates/local/ are still on v23.0.2, which is two years old now. Compared to the most recent ag-grid release, this old version is missing many key functionalities that have since become available, most notably being transaction-based updates. Let's update them with the latest version?

**Comment by WolfgangFahl** [comment]
```
grep @version ag-grid-community.js 
 * @version v23.0.2
```

**Comment by WolfgangFahl** [comment]
For 0.3.0 we should at least try using 23.1.1 and test what happens if we move to more recent versions gradually.

**Comment by WolfgangFahl** [comment]
https://www.ag-grid.com/archive/26.0.0/javascript-data-grid/download/

**Comment by WolfgangFahl** [comment]
https://github.com/ag-grid/ag-grid/tree/v23.2.1/community-modules/all-modules/dist

**Comment by WolfgangFahl** [comment]
```bash
wget https://github.com/ag-grid/ag-grid/blob/v23.2.1/community-modules/all-modules/dist/ag-grid-community.js
```

**Comment by WolfgangFahl** [comment]
@BilliumMoto for the 0.6 milestone v23.2.1 is now used

Please reopen an issue for upgrading further

**Comment by WolfgangFahl** [comment]
18 Jun 2020 - is the release date of the version in use now
