### ISSUE TITLE
As Highcharts 9.3.0 updated, highmap doesn't work anymore

### ISSUE THREAD

**Issue by wy1189** [justpy-org/justpy#315]
I followed this example (https://github.com/elimintz/justpy/issues/163), and it worked well, but as Highcharts 9.3.0 updated, this example doesn't work anymore. 

This is a result from the link.

<img width="697" alt="Screen Shot 2021-10-25 at 13 30 12" src="https://user-images.githubusercontent.com/9031310/138751138-b82c87f7-240f-4014-a0f8-71ffecbd70e9.png">

Instead, a specific version of a js file should be included in the header (e.g., 9.2.2 instead of latest one; 9.3.0).

```
  wp.head_html = """
  <script src="https://code.highcharts.com/maps/9.2.2/highmaps.js"></script>
  <script src="https://code.highcharts.com/mapdata/custom/europe.js"></script>
  """
```

Except for the above issue, I'm the only person who sees this map example weirdly aligned with data labels and map positions?

![Screen Shot 2021-10-25 at 13 49 00](https://user-images.githubusercontent.com/9031310/138752787-f309493f-5cd9-4caa-a55f-13fd10c8904a.png)

I think the labels are somewhat inverted, but I have no idea how I can resolve this issue. Any ideas?

<img width="692" alt="Screen Shot 2021-10-25 at 13 29 19" src="https://user-images.githubusercontent.com/9031310/138751668-26f76c3b-608e-4077-8879-69f79488659c.png">

_Originally posted by @wy1189 in https://github.com/elimintz/justpy/issues/163#issuecomment-951203324_

**Comment by WolfgangFahl** [comment]
I have marked this as a bug and made the example available at http://jpdemo.bitplan.com/ using your workaround. 
Did you find a fix in the meantime?

**Comment by wy1189** [comment]
No. I mean it's still working if I use the 9.2.2 version, but the rotation still happens

**Comment by WolfgangFahl** [comment]
Could you please make this a question in https://stackoverflow.com/search?q=justpy to try to reach a larger community and find out what's going on?

**Comment by wy1189** [comment]
done

**Comment by Luong2705** [comment]
Hi @WolfgangFahl , how is the bug handling going?
Please notice after fixing the error, thanks

**Comment by WolfgangFahl** [comment]
https://stackoverflow.com/a/73486046/1497139 seems helpful. A PR would be welcome  - otherwise this will have to wait until more pressing issues are solved.

**Comment by WolfgangFahl** [comment]
see #685
