### ISSUE TITLE
CORS issue with plotly

### ISSUE THREAD

**Issue by PyT** [justpy-org/justpy#328]
Hello everyone,

Thanks for the great job with JustPy. That's just amazing. 

I'm facing a strange issue. When I accesss a webpage with localhost, no issue with plotly. 
When I access the same page using my PC name, chart is not displayed and facing a CORS issue : 

Access to script at 'https://cdn.plot.ly/plotly-2.1.0.min.js' from origin 'http://XXXXX.fr.intranet:8000' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.

Anyone know how to solve the issue ? 

In the same page, I set an ag-grid grid and no issue at all with this component. 

Tks for your help

**Comment by elimintz** [comment]
Hi,

This is probably an issue with how your environment is configured.
I would suggest setting the host name and port explicitly in the justpy command: https://justpy.io/reference/justpy/
Use port 80 which is the default and almost always available in most environments and provide the the explicit host name.
If this does not solve the problem, you will likely need to configure something in your environment unrelated to justpy

**Comment by WolfgangFahl** [comment]
We might need the CORS Middleware https://www.starlette.io/middleware/ in other CORS cases
