### ISSUE TITLE
aggrid infinite recursion

### ISSUE THREAD

**Issue by theeveventh** [justpy-org/justpy#369]
template/js/aggrid.js line 35: 
```
this.evaluate_formatters(grid_def); 
```
The above line causes an infinite recursion with tutorial example (https://justpy.io/grids_tutorial/database/).  For example, change the table selection from "albums" to "artist". 

(justpy version 0.2.3)

**Comment by elimintz** [comment]
Thank you for flagging this

**Comment by WolfgangFahl** [comment]
duplicate of #467
