### ISSUE TITLE
Bug with number input box in Firefox 73.0.1 (64-bit)

### ISSUE THREAD

**Issue by sprintska** [justpy-org/justpy#38]
Up front, love what I've seen of the framework so far, thanks!

I'm going through the tutorial, and I'm at the Input Type paragraph [here](https://justpy.io/tutorial/input/#the-type-attribute).  I'm running the exact script copy-pasted from the tutorial there.

When I test that page in Firefox 73.0.1 64-bit (no issue in Chrome/Edge), it behaves as expected for the first 16 characters.  Then, starting when I type the 17th character in the input box, it changes the number in the input box after I've typed it.  

For example, I input 1234567890123456 and it works as expected: I have 1234567890123456 in the input box, and in the text box below.  When I type the 17th character, 7, as soon as the debounce expires, the input box changes from "12345678901234567" to "12345678901234568".

Worth noting that the input box appears to populate correctly (at least until the next digit is input after the expiration of the debounce cycle, at which point it populates with the updated contents of the input field).  That makes me suspect there is type checking of the input field itself going on that contains some kind of typing issue.  I'm not a web dev, though, so that's purely conjecture.

**Comment by sprintska** [comment]
Just confirmed--same anomalous behavior on FF 68.6.0 on Android.

**Comment by elimintz** [comment]
Thanks for flagging this. I'll take a look at this issue next week. 

In the meantime, could you please add the line `in1.debounce = 0` to `input_demo` and check. I would like to rule this out as a debounce issue.

**Comment by sprintska** [comment]
Confirmed, same behavior with debounce = 0.

```
async def input_demo(request):
    wp = jp.WebPage()
    in1 = jp.Input(type='number', a=wp, classes=input_classes, placeholder='Please type here')
    in1.debounce = 0
    in1.div = jp.Div(text='What you type will show up here', classes=p_classes, a=wp)
    in1.on('input', my_input)
    return wp
```

Only difference is that instead of waiting for the debounce to lapse, the input character now changes almost immediately. The delay in the change is now the round-trip latency to the server (tested by increasing LATENCY in justpy.env), suggesting a server-side issue.

I'll do some more digging if I get a chance tonight.

**Comment by platinops** [comment]
Hi Eli, did you manage to check this? I get a similar issue on Firefox 68.10.0esr following the [login example](https://justpy.io/tutorial/sessions/#login-example) in [the sessions tutorial](https://justpy.io/tutorial/sessions/).

As soon as I fill in a username and password, I get a Firefox pop-up requesting whether I wish to save the login & password, even though I did not yet submit the form.

This only happens on Firefox, no similar issues on Chrome or Edge. But I have never encountered similar issues with Firefox in other login forms.

**Comment by elimintz** [comment]
Anybody has an idea where the difference between Firefox and the other browsers could originate from? I don't use Firefox so am not aware of its foibles.

**Comment by WolfgangFahl** [comment]
![grafik](https://user-images.githubusercontent.com/1336221/185739813-189d0282-2835-4467-9c29-0034f1aa4861.png)
would say fascinating ...

**Comment by WolfgangFahl** [comment]
Confirmed with http://jpdemo.bitplan.com/ and Firefox 103.0.2

**Comment by tholzheim** [comment]
The problem relies in the type handling
https://github.com/justpy-org/justpy/blob/45041188267e692046ab26a53d40dc43969c1532/examples/tutorial/input/input_demo4.py#L12

With input `type=number` the value of the input is converted to a [js Number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number) and thus to a [double-precision 64-bit binary format IEEE 754](https://en.wikipedia.org/wiki/Double_precision_floating-point_format) but this conversion is only applied when updating the page after handling the event. Thus, the event handler receives the unconverted value which is then for certain numbers changed after updating the page.

Example (in python):
```python
In[1]: x=111111111111111120.0
In[2]: int(x)
Out[2]: 111111111111111120

# number that can not be precisely described as float
In[3]: y=111111111111111121.0
In[4]: int(y)
Out[4]: 111111111111111120
```

So when setting the input field to `111111111111111121`  the event handler receives `111111111111111121` and sets the div text accordingly but during the update of the page the value of the input field is converted to js Number and thus is displayed as `111111111111111120`

> see https://www.w3schools.com/jsref/jsref_max_value.asp
