### ISSUE TITLE
remove python 3.6 support

### ISSUE THREAD

**Issue by WolfgangFahl** [justpy-org/justpy#463]
version 0.3.0 may signal this - the CI doesn't run anyway and quite a few libraries don't support 3.6 any more.

**Comment by elimintz** [comment]
I used as a guide for this https://fastapi.tiangolo.com/ 
It still supports 3.6

**Comment by falkoschindler** [comment]
I also think we can stop supporting Python 3.6, since it has officially reached its end of life last year: https://endoflife.date/python.

**Comment by elimintz** [comment]
> I used as a guide for this https://fastapi.tiangolo.com/ It still supports 3.6

I saw a tweet from Sebastian saying he will stop supporting 3.6 from the next versions.
