### ISSUE TITLE
db_test tutorial example - table selection does not work

### ISSUE THREAD

**Issue by WolfgangFahl** [justpy-org/justpy#467]
https://justpy.io/grids_tutorial/database/ is now available in the examples/tutorial directory and automatically downloads the database as outlined in #466. The first table is shown but the selection does not work:
![grafik](https://user-images.githubusercontent.com/1336221/187201040-e82587f6-818f-4212-b8b3-756d74503f79.png)
![grafik](https://user-images.githubusercontent.com/1336221/187201081-791da7a3-d336-4e64-81d1-1b7ed9c954ae.png)

The /city route works 
![grafik](https://user-images.githubusercontent.com/1336221/187201230-2500fcaf-efa7-4502-aedf-eda7f0af25bd.png)

**Comment by elimintz** [comment]
I think I see the problem. The caching mechanism for ag-grid and is probably causing this issue. I'll work on this.

**Comment by WolfgangFahl** [comment]
This is what the javascript debugger says:
```
RangeError: Maximum call stack size exceeded
    at Object.get [as justpyComponents] (vue.js:2:7284)
    at pn.get [as justpyComponents] (vue.js:2:28307)
    at Function.entries (<anonymous>)
    at a.evaluate_formatters (aggrid.js:15:51)
    at a.evaluate_formatters (aggrid.js:19:26)
    at a.evaluate_formatters (aggrid.js:19:26)
    at a.evaluate_formatters (aggrid.js:19:26)
    at a.evaluate_formatters (aggrid.js:19:26)
    at a.evaluate_formatters (aggrid.js:19:26)
    at a.evaluate_formatters (aggrid.js:19:26)
```

**Comment by WolfgangFahl** [comment]
```javascript
 evaluate_formatters(def) {
            if (Array.isArray(def)) {
                for (const element of def) {
                    this.evaluate_formatters(element);
                }
            } else if (typeof def == "object" && def !== null) {
                for (const [key, value] of Object.entries(def)) {
                    if (key.toLowerCase().includes('formatter')) {
                        eval('def[key] = ' + def[key]);
                    }
                    this.evaluate_formatters(value);
                }
            }
        },
```
there is a cut&paste copy version of this in chartjp.js

**Comment by elimintz** [comment]
Yes, and it does not work for ag-grid. At this stage I recommend removing or commenting out line https://github.com/justpy-org/justpy/blob/master/justpy/templates/js/aggrid.js#L35 until we can revisit this. The example will work then.

**Comment by WolfgangFahl** [comment]
closing for the time being
