### ISSUE TITLE
UUID columns in pandas ag-grid breaks event-handlers

### ISSUE THREAD

**Issue by bapowell** [justpy-org/justpy#500]
Continuation of issue #270, which was focused on timestamp columns. This issue is to focus on UUID or other data types that are breaking a pandas ag-grid.

One suggestion for a possible solution is to specify an optional conversion function that would be called for each row item. That would allow the user to specify, in a custom way, how each item gets represented in the row. For example, UUID could be cast to str, Timestamp could be converted to epoch milliseconds, etc.

**Comment by WolfgangFahl** [comment]
Could you please provide a pull request with a proposal. This way you'd also show up in the list of contributors. if you manage to create a unit test (at least checking the conversion function - optionally as a selenium test) this would be great.

**Comment by WolfgangFahl** [comment]
any news on this? I'd love to integrate this into 0.9.x if possible

**Comment by bapowell** [comment]
Started on it a few days ago, but other work priorities precluded working on it. Will try to have a PR in the next few days.

**Comment by WolfgangFahl** [comment]
![grafik](https://user-images.githubusercontent.com/1336221/190845886-4b1cce6d-1318-4052-9c0d-1ed79e109d52.png)

**Comment by WolfgangFahl** [comment]
![issue500-animated](https://user-images.githubusercontent.com/1336221/190847534-b8d37794-d49c-4d79-b949-04930c8ecec4.gif)
