### ISSUE TITLE
psutil missing in dependencies

### ISSUE THREAD

**Issue by tholzheim** [justpy-org/justpy#539]
[psutil](https://pypi.org/project/psutil/) is currently only listed in _optional dependencies_ but it is used by justpy_app thus it should be a _mandatory dependency_.

https://github.com/justpy-org/justpy/blob/bd86caa97383533deda8e2291ea3e43c10bc81bd/pyproject.toml#L58-L65

https://github.com/justpy-org/justpy/blob/bd86caa97383533deda8e2291ea3e43c10bc81bd/jpcore/justpy_app.py#L16

**Comment by WolfgangFahl** [comment]
It's only used for debugging at this time. Is there a way to specify which set of dependencies should be installed.
Currently we use scripts/test as a  workaround measure to install all dependencies. E.g. in my jenkins server i have:
```bash
python3.10 -m venv .venv
source .venv/bin/activate
scripts/install
scripts/test
```
