### ISSUE TITLE
DemoBrowser try it button has incorrect links

### ISSUE THREAD

**Issue by tholzheim** [justpy-org/justpy#542]
demo name is used for the url: 
https://github.com/justpy-org/justpy/blob/4ad0eadd0c9e68b7e14c01a88e19c9d4f1a6c609/examples/demo_browser.py#L205
but the function name is actually mounted:
https://github.com/justpy-org/justpy/blob/4ad0eadd0c9e68b7e14c01a88e19c9d4f1a6c609/jpcore/justpy_app.py#L668-L674

**Comment by WolfgangFahl** [comment]
thx for the fix
