### ISSUE TITLE
Lightning + JustPy

### ISSUE THREAD

**Issue by tchaton** [justpy-org/justpy#564]
Hey there,

At lightning.ai, we recently came across JustPy and we really liked its simple API.

We added an integration to easily use JustPyt with Lightning.ai: https://github.com/Lightning-AI/lightning/pull/15002

It would be great to build a kick-ass ML demo from JustPy Team, so we can learn best practices and help our users to build their own website with it.

Bets,
T.C

**Comment by WolfgangFahl** [comment]
@tchaton - Thomas thanks for stopping by and suggesting such an example. We are currently in the process of revamping our examples and tutorial anyway so this might be a good addition to the task.
