### ISSUE TITLE
use_websockets seems to be no longer working

### ISSUE THREAD

**Issue by sandeep-gh** [justpy-org/justpy#566]
It seems the webpage option to switch between websockets and ajax is no longer supported. From my tests, even if I set `use_websockets=False`, justpy still opens websockets and all event communication goes through that. 

I am thinking of usecase where a websocket connection is not activated until user credentials are verified but it no longer feasible.

**Comment by sandeep-gh** [comment]
We need to update the docs here at https://justpy.io/reference/webpage/. The docs says `use_websockets = False` should be set 
on WebPage instance. But we only check the class variable -- 
```
context = {
            "request": request,
            "page_id": load_page.page_id,
            "justpy_dict": json.dumps(page_dict, default=str),
            "use_websockets": json.dumps(WebPage.use_websockets),
            "options": template_options,
            "page_options": page_options,
            "html": load_page.html,
            "frontend_engine_type": FRONTEND_ENGINE_TYPE,
            "frontend_engine_libs": FRONTEND_ENGINE_LIBS
        }
```
I will create a pull request with updated docs.

**Comment by WolfgangFahl** [comment]
@sandeep-gh  thank you for pointing out this problem

**Comment by WolfgangFahl** [comment]
This is really legacy ugly.  Currently
```python
import justpy as jp
```

will already invoke
```
def justpy(
    func=None,
    *,
    start_server: bool = True,
    websockets: bool = True,
    host: str = HOST,
    port: int = PORT,
    startup=None,
    init_server: bool = True,
    **kwargs,
):
```

**Comment by WolfgangFahl** [comment]
the test reveals that it doesn't work as expected right now the html is
```html
 let justpy_core=new JustpyCore(
                this, // window
                0, // page_id
                'JustPy', // title
                'true', // use_websockets
```
when explicitly having set WebPage.use_websockets to False.

Global variable are so evil ...

**Comment by sandeep-gh** [comment]
Yes, shouldn't be using global variables. For now, being able to set use_websockets per page is probably best. 
Once, the entry point to justpy is settled a bit, a global option to turn off websocket for the entire duration of app can also be given.

**Comment by WolfgangFahl** [comment]
see #685
