### ISSUE TITLE
Document heroku demo app and create small open source repository

### ISSUE THREAD

**Issue by WolfgangFahl** [justpy-org/justpy#574]
Add a Tutorial section for the justpy demo browser in heroku
* https://justpy-demo.herokuapp.com/

Add Info to main tutorial that question / issues should be accompanied with online example e.g. via heroku as in 
https://justpy-demo.herokuapp.com/demo/issue_387_aggrid_tabgroup (when mounted)

**Comment by byzakyz** [comment]
Live demo bedeckt das code 
<img width="931" alt="image" src="https://user-images.githubusercontent.com/95085996/197279453-f2b426c9-b89c-4acb-995a-43c29c9e82a6.png">

**Comment by byzakyz** [comment]
What does the filter for the second column serve? There is only label visible which leads to source code. But there is also a source column which leads to source code. 
<img width="601" alt="image" src="https://user-images.githubusercontent.com/95085996/197281647-f3096830-2fec-4a41-8113-a8b765cd46eb.png">

**Comment by byzakyz** [comment]
All of the try it links leads to the same example. 

Why is there a seperate try it link when trying it is also possible inside the link of name column

**Comment by WolfgangFahl** [comment]
@byzakyz  thanks for trying out. One of the highchart tests seems to have this effect - there is a probably a state problem.
If you set up your own heroku account Tim and i can give you the files needed to to set up your own test environment   restart things on failure.

**Comment by WolfgangFahl** [comment]
https://github.com/justpy-org/justpy/blob/master/docs/blog/heroku.md has the tutorial part

**Comment by WolfgangFahl** [comment]
There will be no separate project since there are only three needed files available at https://github.com/justpy-org/justpy/tree/master/tutorial/heroku
