### ISSUE TITLE
bokeh tutorial example fails

### ISSUE THREAD

**Issue by WolfgangFahl** [justpy-org/justpy#597]
![grafik](https://user-images.githubusercontent.com/1336221/200129556-f50448dc-9ca5-4beb-b1cc-d3216c19859a.png)

**Comment by WolfgangFahl** [comment]
![bokeh](https://user-images.githubusercontent.com/1336221/200132606-80846c71-6330-48a1-9d6a-be1a67a53730.gif)

**Comment by byzakyz** [comment]
This example also shows syntax errors on my interpreter 
![image](https://user-images.githubusercontent.com/95085996/205447023-29d864bf-5562-43e3-8d17-b9e7194c199d.png)
