### ISSUE TITLE
custom_comp_test2.py color orange not working

### ISSUE THREAD

**Issue by byzakyz** [justpy-org/justpy#598]
examples/tutorial/custom_components/custom_comp_test2.py

![image of the issue](https://user-images.githubusercontent.com/95085996/193044506-24d8f084-ccea-46b7-bc35-284d9d088e41.gif)

"bg-{self.bg_color}-500 hover:bg-{self.bg_color}-700 " for color orange doesn't seem to be working

**Comment by tholzheim** [comment]
The color `orange` is not available in tailwind 2.2.7
> see https://v2.tailwindcss.com/docs/background-color for available colors in tailwind 2.2.7

To repair the example we change `orange` to `yellow` which is the closest to orange in the supported tailwind version.
