### ISSUE TITLE
text_colors.py one color not visible

### ISSUE THREAD

**Issue by byzakyz** [justpy-org/justpy#601]
color and its text of the first color in jp.Tailwind.tw_dict['text_color'] is not visible:

![A_animated](https://user-images.githubusercontent.com/95085996/194646550-d531b4fd-f998-4428-8612-8c010185cc8e.gif)

examples/tutorial/tailwind/text_colors.py

**Comment by tholzheim** [comment]
The first text has the color `transparent` so this is working. Problem here seems to be that `orange` and `teal` are not working as expected.
