### ISSUE TITLE
ajax/hello_test.py how to verify ajax is used?

### ISSUE THREAD

**Issue by byzakyz** [justpy-org/justpy#606]
examples/tutorial/ajax/hello_test.py

In tutorial it says I can verify that ajax is used under Network tab. I don't really know what this should look like but I didn't see anything changing. I read that I should identify if ajax is used under the XHR filter but it is empty. Where should I be looking for?

![A-animated](https://user-images.githubusercontent.com/95085996/198144200-69c2a1e1-1211-4bc7-8448-449d8564392d.gif)

**Comment by WolfgangFahl** [comment]
see #566

**Comment by WolfgangFahl** [comment]
see #685
