### ISSUE TITLE
quasar_components/stock_test.py

### ISSUE THREAD

**Issue by byzakyz** [justpy-org/justpy#618]
QBtn will stay in loading state if the "tIcker" input is not existend in yahoo, as an example when the input is "apple" instead of "AAPL"
![A-animated](https://user-images.githubusercontent.com/95085996/201532445-3f17b5b2-323a-4931-b765-c1ad3a909cd4.gif)

examples/quasar_tutorial/quasar_components/stock_test.py

**Comment by tholzheim** [comment]
Example has missing error handling for the cases were the data retrieval fails
