### ISSUE TITLE
calendar_test.py

### ISSUE THREAD

**Issue by byzakyz** [justpy-org/justpy#625]
examples/tutorial/advanced_components/calendar_test.py

Can't add events to other months. When I try to add a new event on a new month, It returns back the previous month after clicking add event

![A-animated](https://user-images.githubusercontent.com/95085996/203419355-a8f49c82-e2ea-4c72-939a-ed2a33d48690.gif)

**Comment by tholzheim** [comment]
`add_event` always adds an event to a predefined date range. To add an event to a new month or date the logic of the example needs to be extended to either allow to select a date range for the event or open a input form to enter this information.

https://github.com/justpy-org/justpy/blob/bcfa92683fee071fada1031f4b8517abd2bbbb6c/examples/tutorial/advanced_components/calendar_test.py#L82-L84
