### ISSUE TITLE
db_test.py

### ISSUE THREAD

**Issue by byzakyz** [justpy-org/justpy#626]
examples/grids_tutorial/database/db_test.py

uses chinook.db which was previously put in gitignore because it was floating around in the directories. Removed it from gitignore and now its under the  jutpy file. I think the example still can't find this database

![image](https://user-images.githubusercontent.com/95085996/203433516-110a2b5e-d82d-4977-8ae6-cd02ccef0629.png)

**Comment by WolfgangFahl** [comment]
@byzakyz  It should be in the .gitignore and the code should use a url or dynamic download to a users home subdirectory instead. I think i already changed another demo in this style and you could get inspiration there.

**Comment by byzakyz** [comment]
> @byzakyz It should be in the .gitignore and the code should use a url or dynamic download to a users home subdirectory instead. I think i already changed another demo in this style and you could get inspiration there.

Which demo is that? There were some other examples where the files should be put under the applications satatic directory like the ![vue components](https://justpy.io/tutorial/advanced_components/). Should this also be changed int the future?

**Comment by WolfgangFahl** [comment]
What actions are left to close this issue?
