### ISSUE TITLE
grid_events/grid_test14.py  'rowDragEnd' not working

### ISSUE THREAD

**Issue by byzakyz** [justpy-org/justpy#630]
examples/grids_tutorial/grid_events/grid_test14.py,
examples/grids_tutorial/grid_events/grid_test15.py

the event 'rowDragEnd' does't seem to be working

**Comment by byzakyz** [comment]
row dragging had to be enabled [link](https://www.ag-grid.com/javascript-data-grid/row-dragging/)

added this line:
![image](https://user-images.githubusercontent.com/95085996/204145094-ca38d14d-06bf-4ad6-8464-68db45f1ba39.png)

Know I can drag the rows but when I do a sort or filtering, the row dragging is not possible anymore until the filter or sort is gone. see:

![A-animated](https://user-images.githubusercontent.com/95085996/204145150-7989dd16-597d-469c-8dc9-48f3502c391e.gif)

I don't know if this is an expected behaviour

**Comment by tholzheim** [comment]
After filtering the dragging is disabled by design (see https://www.ag-grid.com/javascript-data-grid/row-dragging/#example-events )
To be able to drag the rows after filtering AgGrid needs to be configured differently.
