### ISSUE TITLE
field_evaluation/grid_test9.py grid hierarchy not working 

### ISSUE THREAD

**Issue by byzakyz** [justpy-org/justpy#631]
grid hierarchy is not not working 

examples/grids_tutorial/field_evaluation/grid_test9.py

![image](https://user-images.githubusercontent.com/95085996/204152027-cdfe7b41-d4e1-4680-a570-8fc5c0314234.png)

**Comment by tholzheim** [comment]
We would need a AgGrid enterprise key to test this example

**Comment by WolfgangFahl** [comment]
Or remove the example if it doesn't work without an enterprise key.

**Comment by WolfgangFahl** [comment]
see #685
