### ISSUE TITLE
url_for in templates/main.html causes blocked loading mixed active content error

### ISSUE THREAD

**Issue by kimgiftww** [justpy-org/justpy#640]
The url_for in this template

https://github.com/justpy-org/justpy/blob/48c3e857461ebeeea05ac65ebe7f72ff49ae63af/justpy/templates/main.html

resulted in this blocked loading mixed active content error

https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#warnings_in_firefox_web_console

which was caused by

https://github.com/encode/starlette-example/issues/6

but seemed to be fixed in

https://github.com/encode/uvicorn/issues/369

However, this is still not resolved in JustPy which make an advanced component like this one

https://justpy.io/tutorial/advanced_components/#fullcalendar-example

unable to be deployed in public server.

Is there a way to make url_for return an https instead of http?

**Comment by WolfgangFahl** [comment]
Could you please make a unit test for this to show what the problem exactly is and why we need to fix it in justpy and not upstream?

**Comment by WolfgangFahl** [comment]
see #685
