### ISSUE TITLE
Move example resources to example folder

### ISSUE THREAD

**Issue by tholzheim** [justpy-org/justpy#642]
currently a few resources are on the parent folder of the project 
* https://github.com/justpy-org/justpy/blob/master/papillon.jpg
* https://github.com/justpy-org/justpy/tree/master/components

but are only used by some examples. These resources should be moved to the examples folder or to the example itself.

For the static_test the problem of the static folder in the context of the demo_browser needs to be solved.
https://github.com/justpy-org/justpy/blob/7e49c1dc69c490cc17a47f66d0ccad329c7383a3/examples/tutorial/static/static_test.py#L4-L7

**Comment by WolfgangFahl** [comment]
see #685
