### ISSUE TITLE
Heroku demos are offline

### ISSUE THREAD

**Issue by strongly-typed** [justpy-org/justpy#654]
E.g. the [Tailwind and JustPy live demo](https://justpy-demo.herokuapp.com/demo/hello_world3) linked from the [documentation](https://justpy.io/tutorial/basic_concepts/#tailwind-and-justpy) is down.

I moved to render.com after Heroku discontinued their free tier.

**Comment by WolfgangFahl** [comment]
see https://github.com/heroku/roadmap/issues/126

**Comment by WolfgangFahl** [comment]
We are not waiting for heroku any more see #649
Demos are now at http://justpy-demo.bitplan.com
