### ISSUE TITLE
In QSelect multiple option is not working as expected

### ISSUE THREAD

**Issue by sanket-parte** [justpy-org/justpy#701]
### Discussed in https://github.com/justpy-org/justpy/discussions/697

<div type='discussions-op-text'>

<sup>Originally posted by **sanket-parte** August 23, 2023</sup>
Hello everyone,

We are currently utilizing the QSelect widget within a form, specifically with the multiple=true argument enabled. However, we've encountered an issue where, upon selecting multiple options in the QSelect dropdown, the widget does not transmit all the selected option IDs to the backend upon form submission. Strangely, it only seems to send a single ID (the ID of the first selected option) in string format. Consequently, we're unable to successfully store and save multiple selected options in our database.

Here's the QSelect widget definition for reference:
![select_role_def](https://github.com/justpy-org/justpy/assets/43114999/c57423c3-118d-4755-aa7b-548a066fb6f9)

And here's the corresponding form definition:
![form](https://github.com/justpy-org/justpy/assets/43114999/2f44cf1c-8d65-4e0f-ac6e-6965d6823e34)

For clarity, I've attached an image illustrating the widget after selecting multiple options:
![select_role_widget](https://github.com/justpy-org/justpy/assets/43114999/82674820-b069-4b09-9dde-00cfa3472343)

If anyone has encountered a similar issue or has insights into how to ensure that all selected option IDs are properly transmitted to the backend upon form submission, we would greatly appreciate your assistance.

Thank you in advance for your time and expertise.
</div>

**Comment by WolfgangFahl** [comment]
see #685
